---
- name: Creates backend directory
  file:
    path: ~/backend
    state: directory
    mode: 0755
- name: Upload app 
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz
- name: Install dependencies
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm install -g pm2
    ls
    cd ~/backend
    ls
    tar -vxf artifact.tar.gz
- name: Start backend
  shell:  |
    ls
    cd ~/backend
    ls
    npm install
    pm2 stop default
    pm2 start npm -- run start
    cd dist
    ls
    pm2 start main.js --update-env